/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package threes.main;

import java.awt.BorderLayout;
import java.awt.Insets;
import javax.swing.JLabel;
import threes.game.GameBoardPanel;
import threes.game.GameStatus;
import threes.game.NextBlockPanel;
import threes.listener.MouseListener;
import threes.music.GameMusic;

/**
 *
 * @author Legend
 */
public class ThreesFrame extends javax.swing.JFrame {
    private final MouseListener mouseListener;
    private final GameMusic musicPlay; 
    private boolean isMusicPlay = false;
    
    /**
     * Creates new form ThreesFrame
     */
    
    public ThreesFrame() {
        initComponents();
        initMyComponents();
        //setTitle("Threes!");
//        ImageIcon icon = new ImageIcon("app_icon.png");  
//        Image image = icon.getImage();
        this.musicPlay = new GameMusic(GameMusic.class.getResource("ThreesOST.wav"));
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("app_icon.png")).getImage());
        musicPlay.start(); //BGM plays once. 
        isMusicPlay = true;
        mouseListener = new MouseListener(this);
        this.addMouseListener(mouseListener);
        this.addMouseMotionListener(mouseListener);
    }

    private void initMyComponents() {
        //gameBoardFrame.setBorder(BorderFactory.createEtchedBorder());
        gameBoard = new GameBoardPanel();
        gameBoard.setVisible(true);
        gameBoardFrame.setLayout(new BorderLayout());
        gameBoardFrame.add(gameBoard,BorderLayout.CENTER);
        
        //nextBlockFrame.setBorder(BorderFactory.createEtchedBorder());
        nextBlockPanel = new NextBlockPanel();
        nextBlockPanel.setVisible(true);
        nextBlockFrame.setLayout(new BorderLayout());
        nextBlockFrame.add(nextBlockPanel,BorderLayout.CENTER);
        

        stopMusicButton.setBorderPainted(false);
        stopMusicButton.setMargin(new Insets(0,0,0,0));//将边框外的上下左右空间设置为0
	stopMusicButton.setIconTextGap(0);//将标签中显示的文本和图标之间的间隔量设置为0
	stopMusicButton.setBorderPainted(false);//不打印边框
	stopMusicButton.setBorder(null);//除去边框
	stopMusicButton.setText(null);//除去按钮的默认名称
	stopMusicButton.setFocusPainted(false);//除去焦点的框
	stopMusicButton.setContentAreaFilled(false);//除去默认的背景填充，下同

        newGameButton.setBorderPainted(false);
        newGameButton.setMargin(new Insets(0,0,0,0));
	newGameButton.setIconTextGap(0);
	newGameButton.setBorderPainted(false);
        newGameButton.setBorder(null);
	newGameButton.setText(null);
	newGameButton.setFocusPainted(false);
	newGameButton.setContentAreaFilled(false);
        
        pack();
    }
    
//    private void readHighScore(){
//        File highscore = new File("highscore");
//        if(!highscore.exists()){
//            OutputStream out;
//            try {
//                out = new FileOutputStream(highscore); //如果文件不存在会自动创建
//                String str="0";
//                byte[] b=str.getBytes();
//                out.write(b);//因为是字节流，所以要转化成字节数组进行输出
//                out.close();
//                this.highScorePanel.setText("0");
//            } catch (FileNotFoundException ex) {
//                Logger.getLogger(ThreesFrame.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (IOException ex) {
//                Logger.getLogger(ThreesFrame.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }else{
//            InputStream in;
//            try {
//                in = new FileInputStream(highscore);
//                byte[] b=new byte[(int) highscore.length()];
//                in.read(b);
//                in.close();
//                String s = new String(b);
//                this.highscorePanel.setText(s);
//            } catch (FileNotFoundException ex) {
//                Logger.getLogger(ThreesFrame.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (IOException ex) {
//                Logger.getLogger(ThreesFrame.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nextBlockLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        gameBoardFrame = new javax.swing.JPanel();
        scoreDisplayLabel = new javax.swing.JLabel();
        stopMusicButton = new javax.swing.JToggleButton();
        newGameButton = new javax.swing.JButton();
        nextBlockFrame = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Threes!");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        nextBlockLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        nextBlockLabel.setForeground(new java.awt.Color(119, 126, 140));
        nextBlockLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextBlockLabel.setText("next");

        scoreLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(119, 126, 140));
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel.setText("stats");

        gameBoardFrame.setBackground(new java.awt.Color(187, 217, 217));

        javax.swing.GroupLayout gameBoardFrameLayout = new javax.swing.GroupLayout(gameBoardFrame);
        gameBoardFrame.setLayout(gameBoardFrameLayout);
        gameBoardFrameLayout.setHorizontalGroup(
            gameBoardFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        gameBoardFrameLayout.setVerticalGroup(
            gameBoardFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        scoreDisplayLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 32)); // NOI18N
        scoreDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        stopMusicButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/threes/game/musicon.png"))); // NOI18N
        stopMusicButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/threes/game/musichover.png"))); // NOI18N
        stopMusicButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/threes/game/musicpress.png"))); // NOI18N
        stopMusicButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/threes/game/musicoff.png"))); // NOI18N
        stopMusicButton.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/threes/game/musicpress.png"))); // NOI18N
        stopMusicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopMusicButtonActionPerformed(evt);
            }
        });

        newGameButton.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        newGameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/threes/game/newgame.png"))); // NOI18N
        newGameButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/threes/game/newgamepress.png"))); // NOI18N
        newGameButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/threes/game/newgamepress.png"))); // NOI18N
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        nextBlockFrame.setBackground(new java.awt.Color(249, 249, 249));

        javax.swing.GroupLayout nextBlockFrameLayout = new javax.swing.GroupLayout(nextBlockFrame);
        nextBlockFrame.setLayout(nextBlockFrameLayout);
        nextBlockFrameLayout.setHorizontalGroup(
            nextBlockFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        nextBlockFrameLayout.setVerticalGroup(
            nextBlockFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(gameBoardFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stopMusicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scoreDisplayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nextBlockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nextBlockFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextBlockFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextBlockLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scoreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scoreDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stopMusicButton))
                    .addComponent(gameBoardFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopMusicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopMusicButtonActionPerformed
        // TODO add your handling code here:
        if(isMusicPlay) {
            musicPlay.stop();
            isMusicPlay = false;
        }
        else {
            musicPlay.start();
            isMusicPlay = true;
        }
    }//GEN-LAST:event_stopMusicButtonActionPerformed

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        // TODO add your handling code here:
        startGame();
    }//GEN-LAST:event_newGameButtonActionPerformed

    private void startGame() {
        status = new GameStatus();
        scoreDisplayLabel.setText(" ");
        gameBoard.setStatus(status);
        gameBoard.repaint();
        nextBlockPanel.setStatus(status);
        nextBlockPanel.repaint();
    }
    
    public JLabel getNextBlockLabel(){
        return nextBlockLabel;
    }
    
    public GameBoardPanel getGameBoardPanel(){
        return gameBoard;
    }
    
    public JLabel getScorePanel(){
        return scoreDisplayLabel;
    }
    
    public NextBlockPanel getNextBlockPanel(){
        return nextBlockPanel;
    }
//    
//    public JLabel getHighscorePanel(){
//        return highscorePanel;
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        System.setProperty("awt.useSystemAAFontSettings", "on"); 
        System.setProperty("swing.aatext", "true"); 
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ThreesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ThreesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ThreesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ThreesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ThreesFrame().setVisible(true);
//            }
//        });
        
        java.awt.EventQueue.invokeLater(() -> {
            new ThreesFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gameBoardFrame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newGameButton;
    private javax.swing.JPanel nextBlockFrame;
    private javax.swing.JLabel nextBlockLabel;
    private javax.swing.JLabel scoreDisplayLabel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JToggleButton stopMusicButton;
    // End of variables declaration//GEN-END:variables
    private GameBoardPanel gameBoard;
    private GameStatus status;
    private NextBlockPanel nextBlockPanel;
}
